source $ZDOTDIR/.aliases.zsh
source ../../../env.sh

alias qc='ssh $QC_SSH_PARAMS'

# initialize starship
eval "$(starship init zsh)"

ff

# initialize completion system
autoload -U compinit ; compinit

setopt AUTO_CD COMPLETE_ALIASES NO_BEEP

# allow use of control as a modifier key for shortcuts
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^H' backward-kill-word
bindkey '5~' kill-word

# pnpm (autogenerated)
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

export PATH=$PATH:/home/m/.spicetify

# pnpm
<<<<<<< HEAD
#if [ -d /home/marceline ]
#then
#    export PNPM_HOME="/home/marceline/.local/share/pnpm"
#    case ":$PATH:" in
#      *":$PNPM_HOME:"*) ;;
#      *) export PATH="$PNPM_HOME:$PATH" ;;
#    esac
#else
#    export PNPM_HOME="/home/m/.local/share/pnpm"
#    case ":$PATH:" in
#        *":$PNPM_HOME:"*) ;;
#        *) export PATH="$PNPM_HOME:$PATH" ;;
#    esac
#fi
=======
# if [ -d /home/marceline ]
# then
#     export PNPM_HOME="/home/marceline/.local/share/pnpm"
#     case ":$PATH:" in
#       *":$PNPM_HOME:"*) ;;
#       *) export PATH="$PNPM_HOME:$PATH" ;;
#     esac
# elif [ -d /home/m ]
# then
#     export PNPM_HOME="/home/m/.local/share/pnpm"
#     case ":$PATH:" in
#         *":$PNPM_HOME:"*) ;;
#         *) export PATH="$PNPM_HOME:$PATH" ;;
#     esac
# fi
>>>>>>> 3ef7eaf (this doesnt work yet but i need to pull)
# pnpm end
