source $ZDOTDIR/.aliases.zsh

# load sensitive information from an external zsh file -- DO NOT TRACK THIS FILE
source $ZDOTDIR/.env.zsh

# initialize starship
eval "$(starship init zsh)"

ff

# initialize completion system
autoload -U compinit ; compinit

setopt AUTO_CD COMPLETE_ALIASES NO_BEEP

# allow use of L-ctrl as a modifier key for shortcuts
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^H' backward-kill-word
bindkey '5~' kill-word

export EDITOR="nano"
export VISUAL="nano"
export TERMINAL="konsole"
export N_PREFIX="$HOME/.local/share/n"
export PROJECT_DIR="$HOME/projects"
export INSTANCE="$HOME/.local/share/PrismLauncher/instances/colon-three/"

export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=6900 # max 10000

# does not work if exported from .zshenv; this line must stay in this file
export PATH="$PATH:$HOME/.cargo/bin:$HOME/.local/bin:$N_PREFIX/bin"

# pnpm (autogenerated)
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
