source $ZDOTDIR/.aliases.zsh

# load sensitive information from an external zsh file -- DO NOT TRACK THIS FILE
source $ZDOTDIR/.env.zsh
alias qc='ssh $QC_USER@$QC_HOSTNAME -p $QC_PORT'

# initialize starship
eval "$(starship init zsh)"

ff

# initialize completion system
autoload -U compinit ; compinit

setopt AUTO_CD COMPLETE_ALIASES NO_BEEP

# allow use of control as a modifier key for shortcuts
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey '^H' backward-kill-word
bindkey '5~' kill-word

# pnpm (autogenerated)
export PNPM_HOME="$HOME/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

export PATH=$PATH:/home/m/.spicetify

# pnpm
# if [ -d /home/marceline ]
# then
#     export PNPM_HOME="/home/marceline/.local/share/pnpm"
#     case ":$PATH:" in
#       *":$PNPM_HOME:"*) ;;
#       *) export PATH="$PNPM_HOME:$PATH" ;;
#     esac
# elif [ -d /home/m ]
# then
#     export PNPM_HOME="/home/m/.local/share/pnpm"
#     case ":$PATH:" in
#         *":$PNPM_HOME:"*) ;;
#         *) export PATH="$PNPM_HOME:$PATH" ;;
#     esac
# fi
# pnpm end
